# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])
a

array([10, 20, 30])

In [3]:
a[0]

10

In [4]:
a[0:2]

array([10, 20])

In [5]:
a = np.array([[10,20,30],[100,200,300]])
a

array([[ 10,  20,  30],
       [100, 200, 300]])

In [6]:
a[0,2]

30

In [7]:
a.mean()

110.0

## Media das linhas (0) e das colunas (1)

In [8]:
a.mean(0)

array([ 55., 110., 165.])

In [9]:
a.mean(1)

array([ 20., 200.])

## Matrizes de zeros e ones

Cria matriz de zeros, com duas linhas e tres colunas

In [10]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
a[0,1] = 3
a

array([[0., 3., 0.],
       [0., 0., 0.]])

In [12]:
a[5,0] = 1

IndexError: index 5 is out of bounds for axis 0 with size 2

In [13]:
a = np.ones([4,3])
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Leitura de arquivo Excel com numpy

In [14]:
import pandas as pd
import numpy as np

pessoas = pd.read_excel('caso_estudo.xlsx', sheet_name='pessoas')
pessoas = np.array(pessoas)

pessoas

array([[1, 'Lavinia Sousa', 'F', 18],
       [2, 'Caio Pereira', 'M', 28],
       [3, 'Júlio Azevedo', 'M', 32],
       ...,
       [998, 'Lara Oliveira', 'F', 24],
       [999, 'Julian Cunha', 'M', 43],
       [1000, 'Gustavo Barbosa', 'M', 23]], dtype=object)

Ou em uma unica linha, ja converter uma tabela para um array do numpy

In [16]:
pessoas = np.array(pd.read_excel('caso_estudo.xlsx', sheet_name='pessoas'))
pessoas

array([[1, 'Lavinia Sousa', 'F', 18],
       [2, 'Caio Pereira', 'M', 28],
       [3, 'Júlio Azevedo', 'M', 32],
       ...,
       [998, 'Lara Oliveira', 'F', 24],
       [999, 'Julian Cunha', 'M', 43],
       [1000, 'Gustavo Barbosa', 'M', 23]], dtype=object)

In [19]:
array_de_idades = pessoas[:,3]
soma_das_idades = np.sum(array_de_idades)
soma_das_idades

33909

In [21]:
pessoas[pessoas[:,1] == 'Caio Pereira']

array([[2, 'Caio Pereira', 'M', 28]], dtype=object)

In [23]:
pessoas[pessoas[:,2] == 'M']

array([[2, 'Caio Pereira', 'M', 28],
       [3, 'Júlio Azevedo', 'M', 32],
       [6, 'Felipe Almeida', 'M', 31],
       ...,
       [994, 'Eduardo Costa', 'M', 34],
       [999, 'Julian Cunha', 'M', 43],
       [1000, 'Gustavo Barbosa', 'M', 23]], dtype=object)

Only ages when sex is 'M'

In [25]:
male_ages = pessoas[pessoas[:,2] == 'M', 3]
min_age = np.min(male_ages)
max_age = np.max(male_ages)
mean_age = np.mean(male_ages)

print(min_age)
print(max_age)
print(mean_age)

18
50
34.05577689243028
